# Generated by Django 3.0.8 on 2020-08-04 09:31

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('slider_block', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', max_length=999, required=False))])))])), ('big_text_section_block', wagtail.core.blocks.StructBlock([('text_block_top', wagtail.core.blocks.TextBlock(required=False)), ('text_block_top_subtext', wagtail.core.blocks.TextBlock(max_length=999, required=False))])), ('category_carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=150, required=False)), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('category_title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=255, required=False))])))])), ('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=55, required=True)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('banners_block', wagtail.core.blocks.StructBlock([('title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_left_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_left', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('left_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500)), ('title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_right_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_right', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('right_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500))])), ('recent_works', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=250)), ('background_color_grey', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('works', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('link_title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False))])))])), ('trustpilot_widget', streams.blocks.TrustPilotWidget())], blank=True, null=True)),
                ('content_en', wagtail.core.fields.StreamField([('slider_block', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', max_length=999, required=False))])))])), ('big_text_section_block', wagtail.core.blocks.StructBlock([('text_block_top', wagtail.core.blocks.TextBlock(required=False)), ('text_block_top_subtext', wagtail.core.blocks.TextBlock(max_length=999, required=False))])), ('category_carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=150, required=False)), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('category_title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=255, required=False))])))])), ('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=55, required=True)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('banners_block', wagtail.core.blocks.StructBlock([('title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_left_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_left', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('left_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500)), ('title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_right_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_right', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('right_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500))])), ('recent_works', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=250)), ('background_color_grey', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('works', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('link_title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False))])))])), ('trustpilot_widget', streams.blocks.TrustPilotWidget())], blank=True, null=True)),
                ('content_es', wagtail.core.fields.StreamField([('slider_block', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', max_length=999, required=False))])))])), ('big_text_section_block', wagtail.core.blocks.StructBlock([('text_block_top', wagtail.core.blocks.TextBlock(required=False)), ('text_block_top_subtext', wagtail.core.blocks.TextBlock(max_length=999, required=False))])), ('category_carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=150, required=False)), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('category_title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=255, required=False))])))])), ('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(help_text='To highlight the word into red please put it inside these tags: <b>…text…</b>', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=55, required=True)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('banners_block', wagtail.core.blocks.StructBlock([('title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_left_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_left_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_left', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('left_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500)), ('title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('sub_title_right_banner', wagtail.core.blocks.CharBlock(required=False)), ('image_right_banner', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt_right', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('right_banner_link_url', wagtail.core.blocks.CharBlock(blank=True, max_length=500))])), ('recent_works', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=250)), ('background_color_grey', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('works', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('link_title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False))])))])), ('trustpilot_widget', streams.blocks.TrustPilotWidget())], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SearchBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_type_text', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_type_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_type_text_es', models.CharField(blank=True, max_length=255, null=True)),
                ('select_store_text', models.CharField(blank=True, max_length=255, null=True)),
                ('select_store_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('select_store_text_es', models.CharField(blank=True, max_length=255, null=True)),
                ('search_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('search_button_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('search_button_text_es', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Search Bar',
                'verbose_name_plural': 'Search Bars',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('partner_title', models.CharField(max_length=100)),
                ('partner_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_icon_text', models.TextField(blank=True, null=True)),
                ('location_icon_text_en', models.TextField(blank=True, null=True)),
                ('location_icon_text_es', models.TextField(blank=True, null=True)),
                ('location_icon_mobile_text', models.TextField(blank=True, null=True)),
                ('location_icon_mobile_text_en', models.TextField(blank=True, null=True)),
                ('location_icon_mobile_text_es', models.TextField(blank=True, null=True)),
                ('phone_icon_text', models.TextField(blank=True, null=True)),
                ('phone_icon_text_en', models.TextField(blank=True, null=True)),
                ('phone_icon_text_es', models.TextField(blank=True, null=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(blank=True, max_length=300, null=True)),
                ('top_text_en', models.CharField(blank=True, max_length=300, null=True)),
                ('top_text_es', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('location_en', models.TextField(blank=True, null=True)),
                ('location_es', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('phone_number_en', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_es', models.CharField(blank=True, max_length=50, null=True)),
                ('bottom_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('bottom_text_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('bottom_text_es', models.CharField(blank=True, max_length=2000, null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=200, null=True)),
                ('copyright_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('copyright_text_es', models.CharField(blank=True, max_length=200, null=True)),
                ('american_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('discover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('mastercard_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('visa_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
