# Generated by Django 3.0.9 on 2020-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200820_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='cart_title_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='cart_title_es',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='checkout_button_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='checkout_button_es',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='item_added_text_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='item_added_text_es',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='remove_button_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='remove_button_es',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
