# Generated by Django 3.0.9 on 2020-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200827_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='go_to_google_maps',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
