# Generated by Django 3.0.10 on 2020-09-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0012_auto_20200902_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='svg_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
