# Generated by Django 3.0.11 on 2021-02-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210211_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='close_menu_button_text',
        ),
        migrations.RemoveField(
            model_name='header',
            name='close_menu_button_text_en',
        ),
        migrations.RemoveField(
            model_name='header',
            name='close_menu_button_text_es',
        ),
    ]
