# Generated by Django 3.0.11 on 2021-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210211_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='partner_link',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
