# Generated by Django 3.0.10 on 2020-09-09 13:43

from django.db import migrations, models
import django.db.models.deletion
import my_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200908_0815'),
        ('my_store', '0002_auto_20200903_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystore',
            name='related_store',
            field=models.ForeignKey(blank=True, default=my_store.models.default_related_store, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='product.Location'),
        ),
    ]
