# Generated by Django 3.0.11 on 2021-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0017_auto_20210311_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='schema_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
