# Generated by Django 3.0.11 on 2022-08-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0023_auto_20220816_1623'),
        ('my_store', '0024_auto_20220726_1219'),
    ]

    operations = [
    ]
