# Generated by Django 3.0.11 on 2022-09-14 12:17

from django.db import migrations

def copy_statepage_data_to_all_other(apps, schema_editor):
    StatePage = apps.get_model("my_store", "StatePage")
    filled_page = StatePage.objects.exclude(
        content={},
        content_en={},
        content_es={}
    ).first()
    empty_pages = StatePage.objects.filter(
        content={},
        content_en={},
        content_es={}
    )
    empty_pages.update(
        content=filled_page.content,
        content_en=filled_page.content_en,
        content_es=filled_page.content_es
    )


def reverse_statepage_population(apps, schema_editor):
    StatePage = apps.get_model("my_store", "StatePage")
    pages = StatePage.objects.all().exclude(slug='Idaho')
    pages.update(content={}, content_en={}, content_es={})

class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0028_populate_browse_by_category_category_carousel'),
    ]

    operations = [
        migrations.RunPython(
            copy_statepage_data_to_all_other,
            reverse_statepage_population
        ),
    ]
