# Generated by Django 3.0.11 on 2022-10-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0030_auto_20221006_1225'),
        ('my_store', '0025_auto_20220909_1832'),
    ]

    operations = [
    ]
