# Generated by Django 3.0.11 on 2022-10-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0031_merge_20221011_1132'),
        ('my_store', '0031_merge_20221011_1043'),
    ]

    operations = [
    ]
