# Generated by Django 3.0.9 on 2020-08-20 08:00

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpage'),
        ('checkout', '0002_auto_20200819_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content_en',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content_es',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock())], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TestInvoice',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Invoice ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Trailer', verbose_name='Trailer')),
            ],
            options={
                'verbose_name': 'Test Invoice',
                'verbose_name_plural': 'Test Invoices',
            },
        ),
    ]
