# Generated by Django 3.0.9 on 2020-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200820_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinvoice',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Invoice ID'),
        ),
    ]
