# Generated by Django 3.0.11 on 2022-08-04 22:10

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210405_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('ach_payments', wagtail.core.blocks.ChoiceBlock(choices=[('ach_enable', 'ACH Enable'), ('ach_disable', 'ACH Disable')]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content_en',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('ach_payments', wagtail.core.blocks.ChoiceBlock(choices=[('ach_enable', 'ACH Enable'), ('ach_disable', 'ACH Disable')]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkouttnxpage',
            name='content_es',
            field=wagtail.core.fields.StreamField([('main_content', wagtail.core.blocks.StructBlock([('reserved_message', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('long_text', wagtail.core.blocks.RichTextBlock(help_text='Use "<date> for pick up date, <phone> for store phone, <email> for customer email, to insert that values in text dynamically\nEx: "Tnx <email>! Call <phone> till <date>" --> "Tnx example@example.com! Call +1234567890 till June 13, 2077', required=False)), ('back_button', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('confirmation', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('pickup', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('sale_price', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('financing_available', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('social_icons_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Join The TrailersPlus Community', required=False)), ('text', wagtail.core.blocks.CharBlock(default='Stay Up to Date With the Latest and Greatest', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_image_mobile', wagtail.images.blocks.ImageChooserBlock()), ('background_image_alt', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('partners', streams.blocks.PartnersBlock()), ('ach_payments', wagtail.core.blocks.ChoiceBlock(choices=[('ach_enable', 'ACH Enable'), ('ach_disable', 'ACH Disable')]))], blank=True, null=True),
        ),
    ]
