# Generated by Django 3.0.11 on 2022-09-30 21:01

import checkout.models.django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20220822_1528'),
        ('checkout', '0012_auto_20220930_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinvoice',
            name='trailer',
            field=models.ForeignKey(default=checkout.models.django.default_trailer, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Trailer', verbose_name='Trailer'),
        ),
    ]
