# Generated by Django 3.0.9 on 2020-08-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0003_auto_20200812_1522'),
        ('flatpage', '0003_auto_20200812_1049'),
    ]

    operations = [
    ]
