# Generated by Django 3.0.9 on 2020-08-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('flatpage', '0008_auto_20200824_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Og image'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
