# Generated by Django 3.0.9 on 2020-08-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0009_auto_20200824_1349'),
        ('flatpage', '0007_auto_20200822_1928'),
    ]

    operations = [
    ]
