version: '3'
services:
  db:
    image: postgis/postgis:12-3.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    container_name: db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    restart: always
    container_name: memcached

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: tail -f /dev/null
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - memcached
      - celery
    container_name: web

  celery:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: celery -A trailersplus worker -l info
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis
      - memcached
    container_name: celery

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 16543:80
    env_file:
      - .env
    container_name: pgadmin
volumes:
  postgres_data:
