# Generated by Django 3.0.9 on 2020-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='store_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
