# Generated by Django 3.0.9 on 2020-08-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200823_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_sensitive', models.BooleanField(verbose_name='Case Sensitive?')),
                ('filter_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('startswith', 'Starts With'), ('endswith', 'Ends With'), ('regex', 'Regex')], help_text='SQL Regex https://dataschool.com/how-to-teach-people-sql/how-regex-works-in-sql/', max_length=15)),
                ('filter', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Category Filter',
                'verbose_name_plural': 'Category Filters',
            },
        ),
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=25)),
                ('name_es', models.CharField(max_length=30)),
                ('exclude', models.ManyToManyField(related_name='exclude', to='product.CategoryFilter')),
                ('include', models.ManyToManyField(related_name='include', to='product.CategoryFilter')),
            ],
            options={
                'verbose_name': 'Category Map',
                'verbose_name_plural': 'Category Maps',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.CategoryMap', verbose_name='Global Category'),
        ),
    ]
