# Generated by Django 3.0.9 on 2020-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200825_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymap',
            name='slug',
            field=models.SlugField(default='slug', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
