# Generated by Django 3.0.9 on 2020-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categorymap_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymap',
            name='exclude',
            field=models.ManyToManyField(blank=True, null=True, related_name='exclude', to='product.CategoryFilter'),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='include',
            field=models.ManyToManyField(blank=True, null=True, related_name='include', to='product.CategoryFilter'),
        ),
    ]
