# Generated by Django 3.0.9 on 2020-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200825_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['sale_price']},
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='exclude',
            field=models.ManyToManyField(blank=True, related_name='exclude', to='product.CategoryFilter'),
        ),
        migrations.AlterField(
            model_name='categorymap',
            name='include',
            field=models.ManyToManyField(blank=True, related_name='include', to='product.CategoryFilter'),
        ),
    ]
