# Generated by Django 3.0.9 on 2020-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200827_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilter',
            name='field_name',
            field=models.CharField(choices=[('category__web_category', 'Web Category'), ('coupler', 'Coupler')], default='category__web_category__', max_length=25),
        ),
    ]
