# Generated by Django 3.0.9 on 2020-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200827_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='coupler',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
