# Generated by Django 3.0.10 on 2020-09-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200908_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='store_description_directions',
        ),
        migrations.RemoveField(
            model_name='location',
            name='store_spanish_description_directions',
        ),
    ]
