# Generated by Django 3.0.10 on 2020-10-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200924_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Category', verbose_name="Trailer's type"),
        ),
    ]
