# Generated by Django 3.0.10 on 2020-11-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20201016_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymap',
            options={'ordering': ['order', 'slug'], 'verbose_name': 'Category Map', 'verbose_name_plural': 'Category Maps'},
        ),
    ]
