# Generated by Django 3.0.11 on 2021-01-20 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20201127_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='store_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), size=None),
        ),
        migrations.AlterField(
            model_name='trailertranslation',
            name='doors',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddConstraint(
            model_name='trailertranslation',
            constraint=models.UniqueConstraint(fields=('language', 'trailer_id'), name='unique_translation'),
        ),
    ]
