# Generated by Django 3.0.11 on 2021-10-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('product', '0020_trailer_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='trailer',
                    name='sale_date',
                    field=models.DateField(blank=True, db_index=True, null=True),
                ),
                migrations.AlterField(
                    model_name='trailer',
                    name='status',
                    field=models.IntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AlterField(
                    model_name='trailertranslation',
                    name='language',
                    field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], db_index=True, default='EN', max_length=2),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX CONCURRENTLY "product_trailer_sale_date_29298fa1" ON "product_trailer" ("sale_date");
                    """,
                    reverse_sql="""
                    DROP INDEX "product_trailer_sale_date_29298fa1";
                    """
                ),
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX CONCURRENTLY "product_trailer_status_baabc18d" ON "product_trailer" ("status");
                    """,
                    reverse_sql="""
                    DROP INDEX "product_trailer_status_baabc18d";
                    """
                ),
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX CONCURRENTLY "product_trailertranslation_language_5cbc7a72" ON "product_trailertranslation" ("language");
                    """,
                    reverse_sql="""
                    DROP INDEX "product_trailertranslation_language_5cbc7a72";
                    """
                ),
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX CONCURRENTLY "product_trailertranslation_language_5cbc7a72_like" ON "product_trailertranslation" ("language" varchar_pattern_ops);
                    """,
                    reverse_sql="""
                    DROP INDEX "product_trailertranslation_language_5cbc7a72_like";
                    """
                ),
            ],
        ),
    ]