# Generated by Django 3.0.11 on 2021-12-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20211011_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('EXT360', 'ext360'), ('INT360', 'int360')], default='EXT360', max_length=10, verbose_name='image_type')),
                ('url', models.CharField(max_length=255)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Trailer')),
            ],
            options={
                'verbose_name': 'Image360',
                'verbose_name_plural': 'Images360',
            },
        ),
        migrations.AddIndex(
            model_name='image360',
            index=models.Index(fields=['vin'], name='product_ima_vin_id_4dc575_idx'),
        ),
    ]
