# Generated by Django 3.0.11 on 2021-12-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20211230_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image360',
            old_name='uuid_id',
            new_name='id',
        ),
    ]
