# Generated by Django 3.0.11 on 2022-01-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20211230_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image360',
        ),
    ]
