# Generated by Django 3.0.11 on 2022-01-04 02:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_delete_image360'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('image_type', models.CharField(choices=[('EXT360', 'ext360'), ('INT360', 'int360')], default='EXT360', max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Trailer')),
            ],
            options={
                'verbose_name': 'Image360',
                'verbose_name_plural': 'Images360',
            },
        ),
        migrations.AddIndex(
            model_name='image360',
            index=models.Index(fields=['vin'], name='product_ima_vin_id_4dc575_idx'),
        ),
        migrations.AddIndex(
            model_name='image360',
            index=models.Index(fields=['uuid'], name='product_ima_uuid_8dc285_idx'),
        ),
    ]
