# Generated by Django 3.0.11 on 2022-12-12 21:48

from django.conf import settings
from django.db import migrations, models

# def change_merchantno_to_ohio_locations(apps, schema):
#     """
#     Changes the Merchant number for the Ohio locations, since those use a different
#     code.
#     """

#     Location = apps.get_model('product', 'Location')

#     ohio_locations = Location.objects.filter(store_state="OH")

#     for store in ohio_locations:
#         store.uta_merchant = settings.UTA_MERCHANTNO_OHIO
#         store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_murray_to_americanfork'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uta_merchant',
            field=models.CharField(default='0306933001', max_length=100),
        ),
        # migrations.RunPython(change_merchantno_to_ohio_locations),
    ]
