# Generated by Django 3.0.11 on 2022-12-15 14:40

from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations

def create_point_for_locations(apps, schema):
    Location = apps.get_model('product', 'Location')
    stores = Location.objects.all()

    store_list = []
    for store in stores:
        pnt = GEOSGeometry(f"POINT({store.store_long} {store.store_lat})")
        store.point = pnt
        store_list.append(store)

    Location.objects.bulk_update(store_list, ["point"])



class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_location_point'),
    ]

    operations = [
        migrations.RunPython(create_point_for_locations),
    ]
