# Generated by Django 3.0.11 on 2022-12-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20221215_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Location')),
            ],
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='product_ser_name_ae6b70_idx'),
        ),
    ]
