# Generated by Django 3.0.11 on 2022-12-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20221221_1145'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_service_name_location'),
        ),
    ]
