# Generated by Django 3.0.11 on 2023-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20221223_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(default='', max_length=100),
        ),
    ]
