# Generated by Django 3.0.11 on 2023-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20230103_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='podium_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='podium_text_number',
            field=models.CharField(default='(208) 647-4117', max_length=25),
        ),
    ]
