# Generated by Django 3.0.10 on 2020-09-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('site_settings', '0002_auto_20200807_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_code', models.TextField(blank=True, default='')),
                ('body_code', models.TextField(blank=True, default='')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
