# Generated by Django 3.0.9 on 2020-08-06 14:45

from django.db import migrations


def make_many_reviews(apps, schema):
    """
        Adds the Trailer object in ProductReviews.product to the
        many-to-many relationship in  ProductReviews.products
    """
    ProductReviews = apps.get_model('api', 'ProductReviews')

    for review in ProductReviews.objects.all():
        if review.product is not None:
            review.products.add(review.product)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productreviews_products'),
    ]

    operations = [
        migrations.RunPython(make_many_reviews),
    ]
