# Generated by Django 3.0.9 on 2020-08-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200806_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='product',
        ),
    ]
