# Generated by Django 3.0.9 on 2020-08-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productreviews_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustpilotCount',
            fields=[
                ('sku', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
