# Generated by Django 3.0.9 on 2020-09-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trustpilotcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviews',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicereviews',
            options={'ordering': ['-created_at']},
        ),
    ]
