# Generated by Django 3.0.10 on 2020-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200902_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
