# Generated by Django 3.0.11 on 2021-06-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200908_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='copied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
