# Generated by Django 3.0.11 on 2021-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_lowerprice_copied'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerprice',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
