# Generated by Django 3.0.11 on 2021-10-28 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20211011_1640'),
        ('api', '0013_warranty_warrantyphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='vin',
        ),
        migrations.AddField(
            model_name='warranty',
            name='trailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Trailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warranty',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warranty',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyphoto',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
