# Generated by Django 3.0.11 on 2021-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211028_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='photo_desc',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
