# Generated by Django 3.0.11 on 2022-12-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_storedistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedistance',
            name='user_zipcode',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
