# Generated by Django 3.0.11 on 2022-12-12 23:06

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20221212_1706'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
