# Generated by Django 3.0.11 on 2022-12-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_spatial_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreDistance',
        ),
    ]
