# Generated by Django 3.0.11 on 2023-01-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_storedistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='store_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='trailer_length',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='trailer_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
