# Generated by Django 3.0.11 on 2023-01-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230112_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='quantity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='store_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='trailer_length',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='trailer_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
