# Generated by Django 3.0.10 on 2020-09-18 06:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menus',
            field=wagtail.core.fields.StreamField([('main_menu', wagtail.core.blocks.StructBlock([('menus', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('menu_title', wagtail.core.blocks.CharBlock()), ('menu_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('menu_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('special_class', wagtail.core.blocks.BooleanBlock(default=False, help_text='Special Class for PNG Image', required=False)), ('link_url', wagtail.core.blocks.CharBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))])))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menus_en',
            field=wagtail.core.fields.StreamField([('main_menu', wagtail.core.blocks.StructBlock([('menus', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('menu_title', wagtail.core.blocks.CharBlock()), ('menu_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('menu_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('special_class', wagtail.core.blocks.BooleanBlock(default=False, help_text='Special Class for PNG Image', required=False)), ('link_url', wagtail.core.blocks.CharBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))])))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menus_es',
            field=wagtail.core.fields.StreamField([('main_menu', wagtail.core.blocks.StructBlock([('menus', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('menu_title', wagtail.core.blocks.CharBlock()), ('menu_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('menu_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('special_class', wagtail.core.blocks.BooleanBlock(default=False, help_text='Special Class for PNG Image', required=False)), ('link_url', wagtail.core.blocks.CharBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))])))])))]))], blank=True, null=True),
        ),
    ]
