# Generated by Django 3.0.11 on 2021-08-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20210211_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_url_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_url_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
