# Generated by Django 3.0.6 on 2020-06-01 14:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Title")),
                (
                    "basetype",
                    models.CharField(max_length=255, verbose_name="Base Type"),
                ),
                ("description", wagtail.core.fields.RichTextField()),
                (
                    "category_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
    ]
